### ISSUE TITLE
Passing deployment information to the binary

### ISSUE THREAD

**Issue by wjayesh** [wjayesh/coredns-healthcheck#1]
There are more than one ways to deploy the application and knowledge of the approach used would be useful for making decisions inside the app. One way to get this information is through the use of [flags](https://golang.org/pkg/flag/) in Go. 

The health check application can be deployed either as a pod in the cluster or externally. To solve this case, the path to the `kubeconfig` file can be passed as an argument. Then the following code can be used to get the client. 
```go
func getClient(pathToCfg string) (*kubernetes.Clientset, error) {
	var config *rest.Config
	var err error
	if pathToCfg == "" {
		logrus.Info("Using in cluster config; deployed as a pod")
		config, err = rest.InClusterConfig()
	} else {
		logrus.Info("Using out of cluster config; deployed externally")
		config, err = clientcmd.BuildConfigFromFlags("", pathToCfg)
	}
	if err != nil {
		return nil, err
	}
	return kubernetes.NewForConfig(config)
}
```

In addition to that, the user can allow or disallow the creation of additional pods inside their cluster (when the health check application is deployed externally). For this a boolean flag can be passed while executing, say `--allow-pods`

**Alternatives**
We can use a config file to get the same settings. I did not make this the primary choice because:
* There aren't a lot of fields that need to be set.
* If the application is deployed in a container, command-line arguments would be much simpler than using config files, I believe. 

**Questions**
Is this approach right? Have I missed any alternatives?

**Comment by wjayesh** [comment]
@yongtang @greenpau

**Comment by yongtang** [comment]
@WJayesh Thanks, I will take a look. You can always explicitly ping me if you have any questions in the future (didn't receive you note until today).

**Comment by yongtang** [comment]
@WJayesh Overall it looks good to me. I could see you already have quite some code in the repo. What might be missing, is the README.md for instructions on how to build and deploy. That can help others to give it a try.

**Comment by wjayesh** [comment]
@yongtang  Thanks for pointing that out! I will add the README.md file by tomorrow. Plus, I've added some comments on top of the functions to make them more comprehensible. After the README.md is done, please let me know if there's any ambiguity regarding any part of the code.

**Comment by yongtang** [comment]
@WJayesh I could see you have added quite some content in the repo, though I haven't been able to find a guide to build or run the binary yet. Maybe you can add the instructions to README.md? / @greenpau

**Comment by wjayesh** [comment]
@yongtang I have added some instructions for Docker and Kubernetes in the deployment file [here](https://github.com/WJayesh/healthCheck/blob/master/DEPLOYMENT.md). 
Let me know if any important detail is missing.

**Comment by yongtang** [comment]
@WJayesh Ah it is in `DEPLOYMENT.md`. I will take a look, thanks!

By the way, you may want to add a link or a small section in README.md to link to `DEPLOYMENT.md`. I didn't realized the deployment instruction is in another file before.

**Comment by wjayesh** [comment]
@yongtang Sure, I'll put a link right away! Thanks

**Comment by wjayesh** [comment]
I'm closing this issue as we've moved passed passing info to the binary at this point.
