### ISSUE TITLE
Using miekg/dns to query Service and Pod IPs

### ISSUE THREAD

**Issue by wjayesh** [wjayesh/coredns-healthcheck#3]
The Service and the Pod IPs need to be hit to determine their health. This can be accomplished using the dns [library](https://github.com/miekg/dns) for go. 
I have identified an example application that replicates the functionality of `dig`. This is located [here ](https://github.com/miekg/exdns/blob/master/q/q.go) under `miekg/exdns`. 

My idea is as follows:
1) Create a struct with its fields corresponding to the flags in the `q` application. 
2) Rename `main()` method so as to prevent conflict with already existing `main` method. 
3) Pass the struct variable to this method to replicate the flag functionality. 

I think these modifications will allow the use of the standalone `q` application as a part of my healthCheck app. 
Is there something I have overlooked? Are there better alternatives to this approach?

**Comment by wjayesh** [comment]
@yongtang

**Comment by wjayesh** [comment]
I've discovered a few leads on this. Will update shortly

**Comment by wjayesh** [comment]
How about keeping an executable `q` in the directory and then using `exec.Command(executable, args)`  and then `run` to run that binary? 
The executable can be prepared by building q's source.

**Comment by yongtang** [comment]
@WJayesh Looks good 👍 , this is definitely the direction we should try (one standalone binary without other dependency).

**Comment by wjayesh** [comment]
The approach works so I'm closing this issue.
