### ISSUE TITLE
Should the binary be deployed through a DaemonSet?

### ISSUE THREAD

**Issue by wjayesh** [wjayesh/coredns-healthcheck#34]
**Problem**
In v1.3+, the binary will check DNS service availability through all network namespaces. As such, deploying it on a host network on only one of the nodes won't guarantee access to all netns. 

**Questions**
* Should the preferred form of deployment be restricted to `DaemonSet`?
* Are there other ways this can be handled, giving more choice to end users?

**Comment by greenpau** [comment]
> As such, deploying it on a host network on only one of the nodes won't guarantee access to all netns.

In theory, each host can be equipped with this agent. I think it is fine.

**Comment by greenpau** [comment]
@wjayesh , see above.

**Comment by wjayesh** [comment]
> In theory, each host can be equipped with this agent. I think it is fine.

Okay! One question: does this mean that if the binary is deployed externally and not as an agent, the part of the application that goes through the namespaces won't work? 

In that situation, the only way would be querying the DNS service ip and checking the response.

**Comment by wjayesh** [comment]
Or we could ask that the application be deployed strictly as a DaemonSet?

**Comment by yongtang** [comment]
@wjayesh I think this is more of a "best effort". Only need to make sure the program will behave gracefully under different situations.

**Comment by wjayesh** [comment]
@yongtang Understood. I'll keep this in mind.
