### ISSUE TITLE
two choices for entering network namespaces

### ISSUE THREAD

**Issue by wjayesh** [wjayesh/coredns-healthcheck#40]
The binary, deployed on the root network, will have to enter the different network namespaces on the node so that it can check DNS service availability. 

To go about doing this, first, we'll have to extract the container id 
```golang
containerID := pod.Status.ContainerStatuses[0].ContainerID
```
and then the process id 
```shell
pid = "$(docker inspect -f '{{.State.Pid}}' "container_id")"
```
After this, there are two choices:
1) [ns](https://github.com/containernetworking/plugins/tree/master/pkg/ns) package from Container Networking:
This package has a method [`Do()`](https://github.com/containernetworking/plugins/tree/master/pkg/ns#do-the-recommended-thing) that takes a `netns` object and then executes functions in that namespace. 

   A `netns` object can be obtained from the command `ns.GetNS(path)` where `path` could be constructed using the `pid` we 
   obtained earlier.
   ```
   path = "/proc/$pid/ns/net"
   ```

2) [nsenter ](https://man7.org/linux/man-pages/man1/nsenter.1.html):
This can also be used to execute operations inside a namespace using the command
   ```sh
   nsenter -t "container-pid" -n "command"
   ```

>I'm not using `ip netns exec` as I had initially planned as the steps above are better in that they don't require the symlink [hack ](https://platform9.com/blog/container-namespaces-deep-dive-container-networking/)(Step 2). 

### My opinion
I think the ns package option is better since it is implemented in code and the existence of `netns` objects makes the usage easier and intuitive. 

### Question
Should I use `nsenter` instead? I'm not sure I totally understand its [implementation](https://github.com/karelzak/util-linux/blob/master/sys-utils/nsenter.c) but I think it sets the current network namespace to the one specified and then executes the commands, something the `ns` package does in [code](https://github.com/containernetworking/plugins/blob/6eb8e31d215c254a58aab527c94313e8d147242b/pkg/ns/ns_linux.go#L57).

**Comment by greenpau** [comment]
ns sounds better.

**Comment by yongtang** [comment]
@wjayesh As we are approaching the ending phase of CommunityBridge Program, we will need to have a final project report. Can you send a report through email, ideally in 1-2 pages?

**Comment by wjayesh** [comment]
@yongtang I'll prepare one as soon as possible. Is there a fixed template that I need to follow?

**Comment by yongtang** [comment]
@wjayesh A normal report capture the deliverable or results would be good enough.

**Comment by wjayesh** [comment]
I have created a draft report at this [link](https://1drv.ms/w/s!At24Tr7fuZAWhbBnWg9niChVtmH-Wg?e=cu9eR5). Please let me know if it's apt. Thanks!
