### ISSUE TITLE
project layout does not follow a standard

### ISSUE THREAD

**Issue by greenpau** [wjayesh/coredns-healthcheck#5]
@WJayesh , refer to https://github.com/golang-standards/project-layout.

Also, it might make sense to standardize on a name. For example,

* `cmd/coredns-hc/main.go`
* `pkg/coredns-hc/*.go`

Also, it might make sense to standardize on a name. Generally speaking, it might not be a good idea to mix lowercase and uppercase in your github handle as well as `heatlhCheck` repo name.

**Comment by wjayesh** [comment]
The project layout doc is really helpful and I have gone through the naming conventions too. I have changed the name from camelCase to lowercase. I have asked github support for the change in my handle too. 

>cmd/coredns-hc/main.go
pkg/coredns-hc/*.go

Can I have the main package in the root directory instead? I have read the docs on the layout and feel the added nesting might not be necessary. For reference, I looked at the dns [library ](https://github.com/miekg/dns)as well.

**Comment by wjayesh** [comment]
~I am also planning to use [this ](https://github.com/miekg/exdns/blob/master/q/q.go)app from exdns to replicate the `dig` function. Should I place this under the `/vendor` directory?~

**Comment by wjayesh** [comment]
@greenpau I have made some changes to the layout. Can you please take a look and let me know if something's out of place?

**Comment by greenpau** [comment]
> @greenpau I have made some changes to the layout. Can you please take a look and let me know if something's out of place?

* `Wjayesh` => "wjayesh"
* `health-check` => `coredns-healthcheck`
* Remove Wiki from the repository. It is probably better to have everything in `README.md`
* Change `health-check/cmd/q/q.go` to `coredns-healthcheck/cmd/dnsq/main.go`
* Change `health-check/cmd/coredns-hc/main.go` to `coredns-healthcheck/cmd/coredns-healthcheck/main.go`
* Migrate `DEPLOYMENT.md` to `README.md`.
* Set version to 1.0.0  and make a release. See how to release [here](https://github.com/greenpau/caddy-auth-forms/blob/5f8cd10aacd777a7ed2d9d5744fea884acab8829/Makefile#L70-L83)
* Create `assets/docs/images/README.md` (or `assets/docs/images/.gitkeep`) as a placeholder.
* Create visual aids (e.g. diagrams) to help yourself. You could use PlantUML to generate them and the store the images in `assets/docs/images`.

Once completed. Please ping me to review.

**Comment by greenpau** [comment]
@WJayesh , see above! Good job! Also, please send Zoom invite for 1pm EST 6/15. I will have 30 minutes to go over your work.

**Comment by wjayesh** [comment]
Since I changed the repository name to `coredns-healthcheck` before changing my username, that path has been retired and I can't create a repository under `wjayesh/coredns-healthcheck` . 
However, the module name is still `coredns-healthcheck` and redirects have been set up from `coredns-healthcheck` to `coredns-health`.

**Comment by greenpau** [comment]
You can rename the project under settings.
